---
title: "neuronbridger.attempt"
output: html_document
---
imports
```{r}
library(malecns)
library(coconatfly)
library(fafbseg)
library(neuprintr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(stringr)
library(igraph)
library(tidygraph)
library(ggraph)
library(jsonlite)
library(ggplot2)
library(reshape2)
library(Matrix)
library(neuronbridger)
```

get vAB3 MANC ID

```{r}
mba<-mcns_body_annotations()
vAB3.MANC.id <- mba %>%
  filter(grepl('vAB3',synonyms))%>%
  pull(manc_bodyid)%>%
  as.character()%>%
  unique()

PPN1.MANC.id <- mba %>%
  filter(grepl('PPN1',synonyms))%>%
  pull(manc_bodyid)%>%
  as.character()%>%
  unique()

```
  11055


start neuro bridge

```{r}

version <- "v3_4_0"
dataset <- 'by_body'
item <- PPN1.MANC.id[1]
path = sprintf("https://janelia-neuronbridge-data-prod.s3.amazonaws.com/%s/metadata/%s/%s.json?x-id=GetObject", 
      version, dataset, item)
target.metdatata <- fromJSON(path)[[1]]%>%filter(libraryName=='FlyEM_MANC_v1.0'
)

path2 = sprintf("https://janelia-neuronbridge-data-prod.s3.amazonaws.com/%s/metadata/cdsresults/%s.json", 
      version, target.metdatata%>%pull(id))
cds.results <-  fromJSON(path2)$results
scan_mip
neuronbridge_hits
neuronbridge_avoid
```





